version: "3.8"
services:
  web:
    build: ./app
    image: 813141759275.dkr.ecr.eu-north-1.amazonaws.com/workshop2:workshop2_web
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_tutorials_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=nctutorials.cunobf8mmriy.eu-north-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 813141759275.dkr.ecr.eu-north-1.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 813141759275.dkr.ecr.eu-north-1.amazonaws.com/workshop2:workshop2_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
